name: presentation
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain
  initializer:
    path: ../initializer
  shared:
    path: ../shared

  dartz:
  geolocator:
  json_annotation: ^4.9.0

  http: ^0.13.3
  email_validator: ^2.1.17
  firebase_core:

  # State management
  flutter_bloc:

  # UI
  flutter_svg:
  cupertino_icons: ^1.0.8

  # DI
  get_it: 7.7.0
  injectable: 2.4.2
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner:
  flutter_gen_runner:
  freezed:
  injectable_generator:

flutter_gen:
  output: lib/resource/generated
  line_length: 100

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 800
